### ISSUE TITLE
The Chat#path method ignores the Client#new(host:)

### ISSUE THREAD

**Issue by MadBomber** [ksylvest/omniai-openai#42]
I have 3 extensions that I'm working on for OmniAI:
* OmniAI::LocalAI
* OmniAI::Ollama
* OmniAI::OpenRouter

All three providers use the OpenAI API so I'm setting up these classes to inherent/extend from OmniAI::OpenAI

This is in context with my new gem `ai_client` which wraps OmniAI to provide additional flexibility.

One of the things that I just ran into may and may not be a defect within OmniAI::OpenAI::Chat class where the method `path` ignores the `host` parameter when the `OmniAI::OpenAI::Client` is instantiated.

To bypass this problem I have had to add my own `OmniAI::*::Chat#path` method.  Its work nicely; but, I think that a change to `OmniAI::OpenAI::Chat#path` might be a better solution.  What do you think?

**Comment by MadBomber** [comment]
I have abandoned the OmniAI::Ollama and OmniAI::LocalAI namespace clones.  It just does not work.

However, I'm trying to setup access to open_router.ai via the OmniAI::OpenAI framework and that is not working because the endpoint for OR.ai starts `/api/v1`. and within the `Chat` class the `path` method does not take into account that there might be a prefix before the API version.  I thought I might be able to do it using `host: https://open_router.ai/api` but only the dnly the protocol and domain name and port are used.  The rest of the URL is thrown away.... I think.  Will check the code to make sure.

**Comment by MadBomber** [comment]
It looks like these files all have a method `path` that starts the same way with the VERSION ...
```
transcribe.rb
embed.rb
chat.rb
thread/message.rb
thread/run.rb
speak.rb
```

If we had another parameter `api_prefix:` then we could use that option in each of these `path` methods.  That would be sufficient to allow `OmniAI::OpenAI` to be used to access the `open_router.ai` services.

**Comment by MadBomber** [comment]
Just did a quick test.  That modification works allowing OmniAI::OpenAI::Client to support the open_router.ai services.  I will formalize this later with a PR.

**Comment by ksylvest** [comment]
PR has been merged / deployed. The latest release (v1.8.3) has the requested api_prefix:

https://rubygems.org/gems/omniai-openai/versions/1.8.3
